[package]
name = "skia-bindings"
version = "0.2.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "skia"
include = [ "Cargo.toml", "build.rs", "src/**/*.cpp", "src/lib.rs", "skia/include/**/*", "skia/src/**/*" ]

[features]
default = []
vulkan = []

[dependencies]

[build-dependencies]
bindgen = "0.48.1"
cc = "1"